version: '3.8'

services:
    nginx:
      container_name: nginx
      build:
        context: .
        dockerfile: ./nginx/Dockerfile
      ports:
        - "8080:80"
      depends_on:
        - app
      volumes:
        - ./src:/var/www

    app:
      container_name: app
      build:
        context: .
        dockerfile: ./php/Dockerfile
      depends_on:
        - db
      #volumes:
      #  - ./src:/var/www
      #  - ./supervisor/conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      ports:
        - "9000:9000"
      working_dir: /var/www

    db:
      image: mysql
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=test_yh
        - MYSQL_ROOT_PASSWORD=test_yh

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
        - "3333:80"
      depends_on:
        - db

    redis:
        container_name: redis
        image: redis
        ports:
          - "6379:6379"